/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface BlackMarketSchema {
	$schemaRef: string;
	header: {
		uploaderID: string;
		softwareName: string;
		softwareVersion: string;
		/**
	   * Timestamp upon receipt at the gateway. If present, this property will be overwritten by the gateway; submitters are not intended to populate this property.
	   */
		gatewayTimestamp?: string;
		[k: string]: any;
	};
	/**
	 * Contains all properties from the listed events in the client's journal minus Localised strings and the properties marked below as 'disallowed'
	 */
	message: {
		systemName: string;
		stationName: string;
		timestamp: string;
		/**
	   * Commodity name as returned by the MarketSell entry in the Journal
	   */
		name: string;
		/**
	   * Price to sell to the market
	   */
		sellPrice: number;
		/**
	   * Whether the commodity is prohibited at this station
	   */
		prohibited: boolean;
		[k: string]: any;
	};
}
